<?php include(VIEW_PATH.'/partials/header.phtml'); ?>
  <div class="container-fluid py-2">
    <div class="px-5 py-2 mb-4 bg-light rounded-3">
      <div class="container-fluid">
        <h2 class="fw-bold text-center">401 - Unauthorized</h2>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossorigin="anonymous"></script>
<?php include(VIEW_PATH.'/partials/footer.phtml'); ?>